---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryservice
  labels:
    app: discoveryservice
  namespace: rideshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discoveryservice
  template:
    metadata:
      labels:
        app: discoveryservice
    spec:
      containers:
      - name: discoveryservice
        image: aista/eureka
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - hostPort: 8761
          containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discoveryservice
  namespace: rideshare
spec:
  type: NodePort
  ports:
  - port: 8761
  selector:
    app: discoveryservice