---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: loadtest
  labels:
    name: loadtest
  namespace: loadtest
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: loadtest
        image: aista/load-test
        command: ["/bin/sh"]
        args: ["-c", "while true; do locust --host http://frontend.rideshare.dep.cluster.local -f /config/locustfile.py --clients 5 --hatch-rate 5 --num-request 100 --no-web; done"]
      nodeSelector:
        beta.kubernetes.io/os: linux
