---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
  namespace: rideshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3.4.1
        ports:
        - hostPort: 27017
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: rideshare
spec:
  type: NodePort
  ports:
  - port: 27017
  selector:
    app: mongo