---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: userservice
  namespace: rideshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: aista/user-service
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        # ports:
        # - hostPort: 8080
          # containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: rideshare
spec:
  type: NodePort
  ports:
  - port: 8080
    name: userservice
  selector:
    app: userservice