version: '2.3'

services:

  fluentd:
    build: ./fluentd
    container_name: fluentd
    mem_limit: 512M
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    logging:
        driver: "json-file"
        options:
            max-size: 100m
            max-file: "5"

  elasticsearch:
    image: elasticsearch:5.6.11
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:5.6.11
    container_name: kibana
    mem_limit: 512M
    links:
      - elasticsearch
    ports:
      - "5601:5601"
      
  edgeservice:
    image: aista/edge-service
    container_name: edgeservice
    mem_limit: 512M
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER=discoveryservice
    depends_on:
      - discoveryservice
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  notificationservice:
    image: aista/notification-service
    container_name: notificationservice
    mem_limit: 512M
    ports:
      - "32700:32700"
    command: notification-service
    environment:
      - RABBIT_HOST=rabbitmq
      - EUREKA_SERVER=discoveryservice
    depends_on:
      - discoveryservice
      - rabbitmq
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  discoveryservice:
    image: aista/eureka
    container_name: discoveryservice
    mem_limit: 512M
    ports:
      - "8761:8761"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    mem_limit: 512M
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"

  mysqlserver:
    image: mysql:5.7
    container_name: mysqlserver
    mem_limit: 512M
    volumes:
      - mysql-data:/var/lib/mysql:rw
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'user_service'

  userservice:
    image: aista/user-service
    container_name: userservice
    mem_limit: 512M
    depends_on:
      - discoveryservice
      - mysqlserver
    links:
      - fluentd
    ports:
      - '8091:8091'
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  mongo:
    image: 'mongo:3.4.1'
    container_name: mongo
    mem_limit: 512M
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

  gmapsadapter:
    image: aista/gmaps-adapter
    container_name: gmapsadapter
    mem_limit: 512M
    environment:
      - EUREKA_SERVER=discoveryservice
      - RABBIT_HOST=rabbitmq
    ports:
      - '8080'
    depends_on:
      - discoveryservice
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  calculationservice:
    image: aista/calculation-service
    container_name: calculationservice
    mem_limit: 512M
    environment:
      - EUREKA_SERVER=discoveryservice
      - RABBIT_HOST=rabbitmq
    command: ["go", "run", "main.go"]
    ports:
      - '8080'
    depends_on:
      - discoveryservice
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  frontend:
    image: aista/front-end
    container_name: frontend
    mem_limit: 512M
    environment:
      - EUREKA_SERVER=discoveryservice
      - RABBIT_HOST=rabbitmq
    ports:
      - '4200:4200'
    depends_on:
      - discoveryservice
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

volumes:
  mongo:
  mysql-data: